import uuid
from datetime import date, datetime, timezone
from typing import Optional
from sqlalchemy import Date, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.base import TimestampMixin, UUIDMixin


class Recommendation(Base, UUIDMixin, TimestampMixin):
    """Mitigation recommendation generated by AI agent or rule engine."""

    __tablename__ = "recommendations"

    risk_event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("risk_events.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    action_description: Mapped[str] = mapped_column(Text, nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False)
    suggested_owner: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    urgency: Mapped[str] = mapped_column(String(20), default="this_week", nullable=False)  # immediate, today, this_week, optional
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)  # pending, approved, modified, dismissed, snoozed
    decision_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    decided_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    snooze_until: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    risk_event: Mapped["RiskEvent"] = relationship("RiskEvent", back_populates="recommendations")  # type: ignore # noqa: F821
    actions: Mapped[list["Action"]] = relationship("Action", back_populates="recommendation", cascade="all, delete-orphan")


class Action(Base, UUIDMixin, TimestampMixin):
    """Action item approved by PM and tracked through completion."""

    __tablename__ = "actions"

    recommendation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("recommendations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    description: Mapped[str] = mapped_column(Text, nullable=False)
    owner: Mapped[str] = mapped_column(String(200), nullable=False)
    due_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)  # pending, in_progress, completed, overdue
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    recommendation: Mapped[Optional["Recommendation"]] = relationship("Recommendation", back_populates="actions")
    project: Mapped["Project"] = relationship("Project", back_populates="actions")  # type: ignore # noqa: F821

    __table_args__ = (
        Index("ix_actions_project_status", "project_id", "status"),
    )


class Outcome(Base, UUIDMixin):
    """Post-mitigation outcome recorded for a risk event."""

    __tablename__ = "outcomes"

    risk_event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("risk_events.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )
    result: Mapped[str] = mapped_column(String(20), nullable=False)  # yes, partially, no, not_sure
    feedback_comment: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Relationships
    risk_event: Mapped["RiskEvent"] = relationship("RiskEvent", back_populates="outcome")  # type: ignore # noqa: F821
