import {
  Action,
  ActionListResponse,
  AuditLog,
  DataQualityReport,
  DataSource,
  Dependency,
  Milestone,
  Outcome,
  Project,
  Recommendation,
  RiskDetailResponse,
  RiskEvaluationResponse,
  RiskEvent,
  RiskSummaryResponse,
  ThresholdsResponse,
  WorkItem,
} from "@/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1-novapay",
    name: "NovaPay Mobile Checkout",
    key: "NOVA",
    description: "Next-generation payment gateway and mobile wallet integration for EU & US checkout flows.",
    status: "active",
    health: "critical",
    risk_score: 78.5,
    risk_level: "critical",
    confidence_score: 92.0,
    data_quality_score: 94.0,
    active_risks_count: 5,
    created_at: "2026-09-15T08:00:00Z",
    updated_at: "2026-10-09T09:00:00Z",
  },
  {
    id: "p2-analytics",
    name: "Real-time Telemetry & Analytics Engine",
    key: "TELE",
    description: "High-throughput streaming telemetry pipeline for distributed fraud and payment anomaly detection.",
    status: "active",
    health: "at_risk",
    risk_score: 62.0,
    risk_level: "high",
    confidence_score: 88.0,
    data_quality_score: 89.0,
    active_risks_count: 3,
    created_at: "2026-09-20T10:00:00Z",
    updated_at: "2026-10-09T08:30:00Z",
  },
  {
    id: "p3-design-system",
    name: "Design System 2.0 & Component Studio",
    key: "DS2",
    description: "Unified accessible UI component library, token studio, and dark-mode styling primitives.",
    status: "active",
    health: "healthy",
    risk_score: 14.5,
    risk_level: "low",
    confidence_score: 98.0,
    data_quality_score: 99.0,
    active_risks_count: 0,
    created_at: "2026-09-25T11:00:00Z",
    updated_at: "2026-10-09T07:45:00Z",
  },
];

export const MOCK_RISKS: RiskEvent[] = [
  {
    id: "risk-01",
    project_id: "p1-novapay",
    category: "dependency",
    signal_type: "blocked_tasks",
    severity: "critical",
    title: "Critical Blocker: OAuth2 Token Exchange Delays 3DS & Smoke Tests",
    description: "2 downstream payment verification tasks are hard-blocked by overdue bank tokenization gateway API keys.",
    score: 88.0,
    status: "active",
    affected_milestone_id: "m1",
    evidence_count: 4,
    created_at: "2026-10-05T14:20:00Z",
    updated_at: "2026-10-09T08:00:00Z",
    signals: [
      {
        id: "sig-1",
        category: "dependency",
        signal_type: "blocked_tasks",
        severity: "critical",
        value: 2.0,
        threshold: 1.0,
        score: 0.9,
        title: "Downstream Tasks Hard-Blocked",
        description: "2 tasks blocked for >5 business days approaching sprint cutoff",
        created_at: "2026-10-05T14:20:00Z",
      },
      {
        id: "sig-2",
        category: "schedule",
        signal_type: "overdue_tasks",
        severity: "high",
        value: 8.0,
        threshold: 2.0,
        score: 0.85,
        title: "Overdue Upstream Blocker",
        description: "Task #101 'Implement OAuth2 Token Exchange' is 8 days past due date",
        created_at: "2026-10-05T14:20:00Z",
      },
    ],
  },
  {
    id: "risk-02",
    project_id: "p1-novapay",
    category: "schedule",
    signal_type: "milestone_slippage",
    severity: "critical",
    title: "Milestone Slippage: Payment Gateway V2 Cutover at Risk",
    description: "Remaining sprint velocity is insufficient to complete 18 remaining story points prior to target date.",
    score: 82.5,
    status: "active",
    affected_milestone_id: "m1",
    evidence_count: 3,
    created_at: "2026-10-06T10:15:00Z",
    updated_at: "2026-10-09T08:15:00Z",
    signals: [
      {
        id: "sig-3",
        category: "schedule",
        signal_type: "milestone_slippage",
        severity: "critical",
        value: 4.5,
        threshold: 0.0,
        score: 0.82,
        title: "Negative Sprint Runway",
        description: "Estimated milestone completion date slips 4.5 days past target deadline",
        created_at: "2026-10-06T10:15:00Z",
      },
    ],
  },
  {
    id: "risk-03",
    project_id: "p1-novapay",
    category: "capacity",
    signal_type: "workload_concentration",
    severity: "high",
    title: "Key-Person Bottleneck: 68% of In-Flight PRs Assigned to Lead Architect",
    description: "Alice Engineer is assigned to 9 out of 13 active issues and 4 critical PR reviews simultaneously.",
    score: 74.0,
    status: "active",
    affected_milestone_id: "m1",
    evidence_count: 2,
    created_at: "2026-10-07T09:30:00Z",
    updated_at: "2026-10-09T08:30:00Z",
    signals: [
      {
        id: "sig-4",
        category: "capacity",
        signal_type: "workload_concentration",
        severity: "high",
        value: 0.68,
        threshold: 0.4,
        score: 0.74,
        title: "Single Owner Concentration",
        description: "68% of milestone open story points concentrated on single developer",
        created_at: "2026-10-07T09:30:00Z",
      },
    ],
  },
  {
    id: "risk-04",
    project_id: "p1-novapay",
    category: "scope",
    signal_type: "requirement_churn",
    severity: "medium",
    title: "Scope Injection: 5 Unplanned Work Items Added Mid-Sprint",
    description: "Ad-hoc compliance requirements injected into Sprint 14 without scope de-scoping.",
    score: 55.0,
    status: "active",
    affected_milestone_id: "m1",
    evidence_count: 2,
    created_at: "2026-10-07T16:00:00Z",
    updated_at: "2026-10-09T08:45:00Z",
    signals: [],
  },
  {
    id: "risk-05",
    project_id: "p1-novapay",
    category: "quality",
    signal_type: "defect_growth",
    severity: "medium",
    title: "Defect Ratio Spike in Sandbox Payment Webhooks",
    description: "3 high-priority regression bugs reopened following Sandbox SDK upgrade.",
    score: 48.0,
    status: "active",
    affected_milestone_id: "m1",
    evidence_count: 3,
    created_at: "2026-10-08T11:00:00Z",
    updated_at: "2026-10-09T08:50:00Z",
    signals: [],
  },
];

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec-01",
    risk_id: "risk-01",
    action_type: "reassign_dependency",
    title: "Pair-Program on Bank OAuth2 Token Mocking & Unblock 3DS Flow",
    description: "Spin up a local contract mock server for bank OAuth2 token exchange to unblock Bob from completing 3DS verification tests immediately.",
    rationale: "Eliminates hard dependency on external bank credentials while sandbox API keys are finalized by partner operations.",
    suggested_owner: "Alice Engineer & Bob Developer",
    urgency: "immediate",
    status: "suggested",
    confidence_score: 95.0,
    created_at: "2026-10-08T15:00:00Z",
  },
  {
    id: "rec-02",
    risk_id: "risk-01",
    action_type: "scope_adjustment",
    title: "De-scope Non-Critical Checkout UI Modals from Release Cutover",
    description: "Move Issue #104 (Checkout UI banner polish) to Sprint 15 to free 6 story points for payment smoke testing.",
    rationale: "Protects target cutover milestone date without compromising core payment processing security or compliance.",
    suggested_owner: "Product Manager (Anita)",
    urgency: "high",
    status: "suggested",
    confidence_score: 91.0,
    created_at: "2026-10-08T15:00:00Z",
  },
  {
    id: "rec-03",
    risk_id: "risk-01",
    action_type: "delegate_reviews",
    title: "Delegate PR Code Reviews to Secondary Maintainers",
    description: "Reassign 3 pending pull request reviews from Alice to Dave to unblock merging payment webhook handlers.",
    rationale: "Reduces key-person review latency from 72h to <8h.",
    suggested_owner: "Engineering Lead",
    urgency: "medium",
    status: "suggested",
    confidence_score: 87.0,
    created_at: "2026-10-08T15:00:00Z",
  },
];

export const MOCK_ACTIONS: Action[] = [
  {
    id: "act-01",
    project_id: "p1-novapay",
    risk_id: "risk-01",
    recommendation_id: "rec-01",
    title: "Implement Mock Bank OAuth2 Server for Local 3DS Smoke Tests",
    description: "Created wiremock fixture to unblock downstream integration testing",
    owner_name: "Bob Developer",
    status: "in_progress",
    urgency: "immediate",
    due_date: "2026-10-12",
    created_at: "2026-10-08T16:00:00Z",
  },
  {
    id: "act-02",
    project_id: "p1-novapay",
    risk_id: "risk-02",
    recommendation_id: "rec-02",
    title: "Move Banner UI Polish to Sprint 15 Backlog",
    description: "Re-allocated 6 story points from Sprint 14 to Sprint 15",
    owner_name: "Anita PM",
    status: "completed",
    urgency: "high",
    due_date: "2026-10-09",
    completed_at: "2026-10-09T08:30:00Z",
    created_at: "2026-10-08T16:15:00Z",
  },
];

export const MOCK_MILESTONES: Milestone[] = [
  {
    id: "m1",
    project_id: "p1-novapay",
    title: "Payment Gateway V2 Cutover",
    description: "Core payment routing and 3DS authentication cutover",
    status: "open",
    target_date: "2026-10-20",
    start_date: "2026-09-25",
    completed_items_count: 8,
    total_items_count: 14,
    slippage_days: 4,
    created_at: "2026-09-25T00:00:00Z",
  },
  {
    id: "m2",
    project_id: "p1-novapay",
    title: "PCI-DSS Level 1 Audit Readiness",
    description: "Compliance certification and tokenization vault audit",
    status: "open",
    target_date: "2026-11-15",
    start_date: "2026-10-01",
    completed_items_count: 3,
    total_items_count: 9,
    slippage_days: 0,
    created_at: "2026-10-01T00:00:00Z",
  },
];

export const MOCK_DEPENDENCIES: Dependency[] = [
  {
    id: "dep-1",
    project_id: "p1-novapay",
    blocked_item_id: "task-102",
    blocker_item_id: "task-101",
    dependency_type: "blocks",
    blocked_item_title: "Integrate Vault 3DS Authentication Service",
    blocker_item_title: "Implement OAuth2 Token Exchange with Bank Gateway",
    blocked_item_status: "blocked",
    blocker_item_status: "in_progress",
    is_overdue: true,
    created_at: "2026-10-01T00:00:00Z",
  },
  {
    id: "dep-2",
    project_id: "p1-novapay",
    blocked_item_id: "task-103",
    blocker_item_id: "task-102",
    dependency_type: "blocks",
    blocked_item_title: "End-to-End Payment Flow Smoke Tests",
    blocker_item_title: "Integrate Vault 3DS Authentication Service",
    blocked_item_status: "blocked",
    blocker_item_status: "blocked",
    is_overdue: false,
    created_at: "2026-10-02T00:00:00Z",
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud-01",
    project_id: "p1-novapay",
    entity_type: "recommendation",
    entity_id: "rec-01",
    action: "approve",
    actor_id: "user-anita",
    actor_name: "Anita (Product Manager)",
    details: {
      action_created: "act-01",
      owner: "Bob Developer",
      due_date: "2026-10-12",
    },
    created_at: "2026-10-08T16:00:00Z",
  },
  {
    id: "aud-02",
    project_id: "p1-novapay",
    entity_type: "risk_engine",
    entity_id: "risk-01",
    action: "evaluate",
    actor_id: "system",
    actor_name: "RiskZen Risk Engine",
    details: {
      signals_detected: 5,
      composite_score: 78.5,
      health: "critical",
    },
    created_at: "2026-10-08T15:30:00Z",
  },
  {
    id: "aud-03",
    project_id: "p1-novapay",
    entity_type: "data_source",
    entity_id: "src-github",
    action: "sync",
    actor_id: "system",
    actor_name: "GitHub Sync Worker",
    details: {
      items_synced: 42,
      duration_ms: 320,
    },
    created_at: "2026-10-08T15:00:00Z",
  },
];

export const MOCK_DATA_SOURCES: DataSource[] = [
  {
    id: "src-github",
    project_id: "p1-novapay",
    source_type: "github",
    name: "GitHub / novapay-checkout",
    status: "active",
    last_synced_at: "2026-10-09T09:00:00Z",
    created_at: "2026-09-15T08:00:00Z",
    config: {
      owner: "novapay-org",
      repo: "novapay-checkout",
      branch: "main",
    },
  },
  {
    id: "src-budget",
    project_id: "p1-novapay",
    source_type: "csv_budget",
    name: "Q4 Engineering Financial Budget CSV",
    status: "active",
    last_synced_at: "2026-10-08T12:00:00Z",
    created_at: "2026-09-20T10:00:00Z",
    config: {
      filename: "novapay_q4_budget.csv",
    },
  },
];
